on: push

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        fpm-version: ["v0.7.0", "v0.8.0", "latest"]
    env:
      GCC_V: ${{ matrix.fpm-version == 'v0.7.0' && 9 || 10 }} # Install gcc@9 for fpm v0.7.0, otherwise gcc@10

    steps:
      - uses: actions/checkout@v3

      - name: Install compiler (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc@${GCC_V}
          sudo ln -s $(which gfortran-${GCC_V}) $(dirname $(which gfortran-${GCC_V}))/gfortran

      - name: Install compiler (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-gcc-fortran

      - name: setup-fpm
        uses: ./ # Uses action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: ${{ matrix.fpm-version }}

      - name: Test fpm (Ubuntu, macOS)
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
          which gfortran
          gfortran --version
          cd example/hello_world
          fpm test

      - name: Test fpm (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          which gfortran
          gfortran --version
          cd example/hello_world
          fpm test