on: push

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        fpm-version: ["v0.7.0", "v0.8.0", "latest"]
    env:
      GCC_V: 10

    steps:
      - uses: actions/checkout@v3

      # - name: Install compiler 
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt install -y gfortran-${GCC_V}
      #     sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} 100

      - name: Install compiler (macOS)
        if: matrix.os == 'macos'
        run: |
          brew install gcc@${GCC_V}
          sudo ln -s $(which gfortran-${GCC_V}) $(dirname $(which gfortran-${GCC_V}))/gfortran

      - name: Install compiler (Windows)
        if: matrix.os == 'windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-gcc-fortran

      - name: setup-fpm
        uses: ./ # Uses action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: ${{ matrix.fpm-version }}

      - name: test fpm
        run: |
          cd example/hello_world
          fpm test
