on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        fpm-version: ["v0.7.0", "v0.8.0", "latest"]
    env:
      GCC_V: 10

    steps:
      - uses: actions/checkout@v3

      - uses: awvwgk/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: ${{ env.GCC_V }}

      - name: Set up macOS
        if: matrix.os == 'macos-latest' && matrix.fpm-version == 'v0.7.0'
        run: ln -s $(which gfortran-${GCC_V}) $(dirname $(which gfortran-${GCC_V}))/gfortran

      - run: ${{ env.FC }} --version
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}

      - name: fpm-setup
        uses: ./ # Uses action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: ${{ matrix.fpm-version }}

      - name: test fpm
        run: |
          cd example/hello_world
          fpm test
